# Bash Aliases to simplify development and packaging of Bodhi themes

alias bb="./build.sh"

alias arcgreen="git clone https://github.com/thewaiter/enlightenment-arc-theme"
alais ardark="git clone https://github.com/thewaiter/MokshaArcDark"
alias blingbling="git clone https://github.com/thewaiter/etheme-blingbling-e20"
alias blue="git clone https://github.com/thewaiter/MokshaBlueElectric"
alias crema="git clone https://github.com/thewaiter/MokshaCrema" 
alias detour="git clone https://github.com/thewaiter/MokshaDetour"
alias dimensions="git clone https://github.com/thewaiter/MokshaDimensions"
alias forum="git clone https://github.com/thewaiter/MokshaForum"
alias green="git clone https://github.com/thewaiter/MokshaGreen"
alias ice="git clone https://github.com/thewaiter/MokshaIce"
alias kl4k="git clone https://github.com/thewaiter/MokshaKL4K"
alias moonlight="git clone https://github.com/rbtylee/MoonLight"
alias passion="git clone https://github.com/thewaiter/MokshaRedPassion"
alias pink="git clone https://github.com/thewaiter/MokshaPink"
alias japan="git clone https://github.com/thewaiter/MokshaJapan"
alias radiance="git clone https://github.com/thewaiter/MokshaRadiance"
alias seven="git clone https://github.com/thewaiter/MokshaSeven"
alias sunshine="git clone https://github.com/thewaiter/MokshaSunshine"
alias wood="git clone https://github.com/thewaiter/MokshaWoodGrey"
alias vice="git clone https://github.com/hippytaffer/bodhi-visa-versa"
